name: huaweilocation
description: Huawei location plugin
version: 0.0.1
author: Jacob Velarde
repository:
  
environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.jacob.huaweilocation
        pluginClass: HuaweilocationPlugin
      ios:
        pluginClass: HuaweilocationPlugin

